[package]
name = "cytusparser"
version = "0.1.0"
authors = ["Keanu <keanutimmermans8@gmail.com>", "Ignacio <nnubes256@gmail.com>"]
license = "Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
